#version 450 core

layout(local_size_x = 8, local_size_y = 8) in;

#include "_header.inc"

layout(binding = 0, std430) readonly buffer I0 {
	MarchOut dataIn[];
};

#include "_ubo.inc"

ivec2 pixel  = ivec2(gl_GlobalInvocationID.xy);
uint g_index = gl_GlobalInvocationID.x +
               gl_GlobalInvocationID.y*ubo_SIZE.x;

void main() {

    //uint value = dataIn[g_index].voxel;
    //dataIn[g_index].voxel = value;
}